server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/laptop_identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#jwt
jwt:
  secret-key: "leminhhoangleminhhoangleminhhoangleminhhoangleminhhoangleminhhoangleminhhoangleminhhoang"
  token-validity-in-seconds: 300
  refresh-token-validity-in-seconds: 864000

