server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2
        - id: category_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/category/**
          filters:
            - StripPrefix=2
        - id: search_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/search/**
          filters:
            - StripPrefix=2
        - id: brand_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/brand/**
          filters:
            - StripPrefix=2