server:
  port: 8085
  servlet:
    context-path: /search

spring:
  elasticsearch:
    uris: http://localhost:9200
    index:
      products: products
  data:
    elasticsearch:
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: com.laptopexpress.event.dto.ProductEvent:com.laptopexpress.event.dto.UpsertProductEvent